#!/bin/bash
### BEGIN INIT INFO
# Provides: sinkerregistryapid
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop sinker_registry_api 
### END INIT INFO

set -eufo pipefail

DESC="sinker_registry_api daemon"
NAME="sinkerregistryapid"
PIDFILE="/var/run/sinkerregistryapid.pid"
touch $PIDFILE
KPID=$(cat $PIDFILE)

do_start() {
    touch $PIDFILE
    if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
      logger -t info [$NAME] $NAME already running
    else
      cd /srv/sinker_registry_api
      docker-compose up --force-recreate --build & 
      echo $! > $PIDFILE
      docker container prune
      sleep 10
    fi
}

do_stop() {
 echo "Stopping $NAME";
 if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
     kill $KPID
     cd /srv/sinker_registry_api
     docker-compose stop
     docker container prune 
 fi
}

case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   restart)
     do_stop
     do_start
     ;;
   *)
     echo "Usage: /etc/init.d/$NAME start|stop"
     exit 1
     ;;
esac

exit 0

