#!/bin/bash
### BEGIN INIT INFO
# Provides: fileretrievald
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop fileretrieval 
### END INIT INFO

set -eufo pipefail

DESC="fileretrieval daemon"
NAME="fileretrievald"
PIDFILE="/var/run/fileretrievald.pid"
touch $PIDFILE
KPID=$(cat $PIDFILE)

do_start() {
    touch $PIDFILE
    if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
      logger -t info [$NAME] $NAME already running
    else
      cd /srv/fileretrieval
      docker-compose up &
      echo $! > $PIDFILE
      sleep 10
    fi
}

do_stop() {
 echo "Stopping $NAME";
 if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
     kill $KPID
     cd /srv/fileretrieval
     docker-compose stop
 fi
}

case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   restart)
     do_stop
     do_start
     ;;
   *)
     echo "Usage: /etc/init.d/$NAME start|stop"
     exit 1
     ;;
esac

exit 0

