---
sysdig_repo_key_url: "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
sysdig_repo_key_id: "EC51E8C4"

sysdig_files:
  - { src: '../files/sysdigd', dest: '/usr/local/sbin/sysdigd', mode: '0500' }
  - { src: '../files/cleanup_traces.sh', dest: '/usr/local/sbin/cleanup_traces.sh', mode: '0500' }
  - { src: '../files/sysdigd.service', dest: '/etc/systemd/system/sysdigd.service', mode: '0444' }
  - { src: '../files/modified_sysdig_chisel/spy_users.lua', dest: '/usr/share/sysdig/chisels/spy_users.lua', mode: '0444' }

falco_files:
  - { src: '../files/falco.yaml', dest: '/etc/falco.yaml', mode: '0444' }
  - { src: '../files/falco_container_rules.yaml', dest: '/etc/falco_container_rules.yaml', mode: '0444' }
  - { src: '../files/falco.service', dest: '/etc/systemd/system/falco.service', mode: '0444' }
  - { src: '../files/gocode/src/bitbucket.org/fseros/container_recycler/bin/container_recycler', dest: '/usr/local/bin/container_recycler', mode: '0500' }

container_directory: "/var/tmp/image"

container_files:
  - { src: '../files/typical_passwords', dest: "/usr/share/dict/typical_passwords", mode: '0444' }
  - { src: '../files/random_password_100', dest: "/usr/share/dict/random_password_100", mode: '0444' }
  - { src: '../files/random_password_1000000', dest: "/usr/share/dict/random_password_1000000", mode: '0444' }
  - { src: '../files/Dockerfile', dest: "{{ container_directory }}/Dockerfile", mode: '0500' }
  - { src: '../files/Dockerfile-base', dest: "{{ container_directory }}/Dockerfile-base", mode: '0500' }
  - { src: '../files/docker-compose.yml', dest: "{{ container_directory }}/docker-compose.yml", mode: '0500' }
  - { src: '../files/tc_manager.sh', dest: '/usr/local/sbin/tc_manager.sh', mode: '0500' }
  - { src: '../files/containersvc', dest: '/usr/local/sbin/containersvc', mode: '0500' }
  - { src: '../files/containersvc.service', dest: '/etc/systemd/system/containersvc.service', mode: '0444' }


unattended_origins_patterns:
  - 'origin=Debian,codename=${distro_codename},label=Debian-Security'
unattended_package_blacklist: [cowsay, vim, docker-ce, docker, sysdig, falco]
unattended_mail: 'root'