---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart sshd
  service: name=sshd state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
