---
sysdig_repo_key_url: "https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public"
sysdig_repo_key_id: "EC51E8C4"

elasticsearch_directory: "/srv/elasticsearch"
elasticsearch_files:
  - { src: '../files/elasticsearch/docker-compose.yml', dest: "{{elasticsearch_directory}}/docker-compose.yml", mode: '0444' }
  - { src: '../files/elasticsearch/common.yml', dest: "{{elasticsearch_directory}}/common.yml", mode: '0444' }
  - { src: '../files/elasticsearch/elasticsearchd', dest: '/usr/local/sbin/elasticsearchd', mode: '0500' }
  - { src: '../files/elasticsearch/elasticsearchd.service', dest: '/etc/systemd/system/elasticsearchd.service', mode: '0444' }


fileretrieval_directory: "/srv/fileretrieval"
fileretrieval_files:
  - { src: '../files/fileretrieval/docker-compose.yml', dest: "{{fileretrieval_directory}}/docker-compose.yml", mode: '0444' }
  - { src: '../files/fileretrieval/fileretrievald', dest: '/usr/local/sbin/fileretrievald', mode: '0500' }
  - { src: '../files/fileretrieval/fileretrievald.service', dest: '/etc/systemd/system/fileretrievald.service', mode: '0444' }
  - { src: '../files/fileretrieval/logstash', dest: "{{fileretrieval_directory}}", mode: '0555' }

sinkerregistryapi_directory: "/srv/sinker_registry_api"
sinkerregistryapi_files:
  - { src: '../files/sinkerregistryapi/docker-compose.yml', dest: "{{sinkerregistryapi_directory}}/docker-compose.yml", mode: '0444' }
  - { src: '../files/sinkerregistryapi/Dockerfile', dest: "{{sinkerregistryapi_directory}}/Dockerfile", mode: '0444' }
  - { src: '../files/sinkerregistryapi/sinkerregistryapid', dest: '/usr/local/sbin/sinkerregistryapid', mode: '0500' }
  - { src: '../files/sinkerregistryapi/sinkerregistryapid.service', dest: '/etc/systemd/system/sinkerregistryapid.service', mode: '0444' }
  - { src: '../files/sinkerregistryapi/gocode.tgz', dest: "{{sinkerregistryapi_directory}}/gocode.tgz", mode: '0444' }


metadataextractor_directory: "/srv/metadataextractor"
metadataextractor_files:
  - { src: '../files/metadataextractor/docker-compose.yml', dest: "{{metadataextractor_directory}}/docker-compose.yml", mode: '0444' }
  - { src: '../files/metadataextractor/Dockerfile', dest: "{{metadataextractor_directory}}/Dockerfile", mode: '0444' }
  - { src: '../files/metadataextractor/metadataextractord', dest: '/usr/local/sbin/metadataextractord', mode: '0500' }
  - { src: '../files/metadataextractor/metadataextractord.service', dest: '/etc/systemd/system/metadataextractord.service', mode: '0444' }
  - { src: '../files/metadataextractor/srv01metadataextractor.yaml', dest: '{{metadataextractor_directory}}', mode: '0444' }
  - { src: '../files/metadataextractor/srv02metadataextractor.yaml', dest: '{{metadataextractor_directory}}', mode: '0444' }
  - { src: '../files/metadataextractor/gocode.tgz', dest: "{{metadataextractor_directory}}/gocode.tgz", mode: '0444' }


sysdig_files:
   - { src: '../files/modified_sysdig_chisel/spy_users.lua', dest: '/usr/share/sysdig/chisels/spy_users.lua', mode: '0444' }
   - { src: '../files/modified_sysdig_chisel/spy_users.lua', dest: '{{metadataextractor_directory}}/spy_users.lua', mode: '0444' }
