version: "2"

services:
  metadata_extractor_srv01_file:
    build:
      context: . #current dir as build context
      args:
        - CONFIGFILE=srv01metadataextractor.yaml
    image: metadata_extractor_srv01
    command: ./metadata_extractor -v file
    container_name: metadata_extractor_srv01_file
    network_mode: "host"
    restart: always
    volumes:
      - /var/log/traces:/var/log/traces
      
  metadata_extractor_srv02_file:
    build:
      context: . #current dir as build context
      args:
        - CONFIGFILE=srv02metadataextractor.yaml
    image: metadata_extractor_srv02
    command: ./metadata_extractor -v file
    container_name: metadata_extractor_srv02_file
    network_mode: "host"
    restart: always
    volumes:
      - /var/log/traces:/var/log/traces
     
  metadata_extractor_srv01_ssh:
    build:
      context: . #current dir as build context
      args:
        - CONFIGFILE=srv01metadataextractor.yaml
    image: metadata_extractor_srv01
    command: ./metadata_extractor -v ssh -f
    container_name: metadata_extractor_srv01_ssh
    network_mode: "host"
    restart: always
    volumes:
      - /var/log/traces:/var/log/traces
     
  metadata_extractor_srv02_ssh:
    build:
      context: . #current dir as build context
      args:
        - CONFIGFILE=srv02metadataextractor.yaml
    image: metadata_extractor_srv02
    command: ./metadata_extractor -v ssh -f
    container_name: metadata_extractor_srv02_ssh
    network_mode: "host"
    restart: always
    volumes:
      - /var/log/traces:/var/log/traces