version: "2"

services:
  metadata_extractor_srv01_file:
    build:
      context: . #current dir as build context
    image: metadata_extractor
    command: ./metadata_extractor -v file
    container_name: metadata_extractor
    networks:
      - api_net
    volumes:
      - /var/log/traces:/var/log/traces
      - /srv/metadataextractor/srv01metadataextractor.yaml:/go/src/bitbucket.org/fseros/metadata_extractor/.metadata_extractor.yaml

  metadata_extractor_srv02_file:
    build:
      context: . #current dir as build context
    image: metadata_extractor
    command: ./metadata_extractor -v file
    container_name: metadata_extractor
    networks:
      - api_net
    volumes:
      - /var/log/traces:/var/log/traces
      - /srv/metadataextractor/srv02metadataextractor.yaml:/go/src/bitbucket.org/fseros/metadata_extractor/.metadata_extractor.yaml

  metadata_extractor_srv01_ssh:
    build:
      context: . #current dir as build context
    image: metadata_extractor
    command: ./metadata_extractor -v ssh -f
    container_name: metadata_extractor
    networks:
      - api_net
    volumes:
      - /var/log/traces:/var/log/traces
      - /srv/metadataextractor/srv01metadataextractor.yaml:/go/src/bitbucket.org/fseros/metadata_extractor/.metadata_extractor.yaml

  metadata_extractor_srv02_ssh:
    build:
      context: . #current dir as build context
    image: metadata_extractor
    command: ./metadata_extractor -v ssh -f
    container_name: metadata_extractor
    networks:
      - api_net
    volumes:
      - /var/log/traces:/var/log/traces
      - /srv/metadataextractor/srv02metadataextractor.yaml:/go/src/bitbucket.org/fseros/metadata_extractor/.metadata_extractor.yaml

networks:  
  api_net:
    external:
      name: sinkerregistryapi_api_net
