- name: 'add route53 entry'
  route53:
      profile: "superprivydns"
      command: "create"
      zone: "{{ pot_domain }}"
      hosted_zone_id: "Z2BYBPR2EQAAUC"
      overwrite: "yes"
      record: "{{ ansible_hostname ~ '.{{ pot_domain }}' }}"
      type: "A"
      ttl: "300"
      value: "{{ ansible_host }}" 
      wait: "yes" 
  when: "ansible_all_ipv4_addresses |  ipaddr('public')"
  become: false
  delegate_to: 127.0.0.1
  tags: 'common::route53'
