- name: Create swap space
  command: fallocate --length 1GiB /extraswap
  when: ansible_swaptotal_mb < 1


- name: swap permissions
  command: chmod 0600 /extraswap
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present
  when: ansible_swaptotal_mb < 1

- name: Turn swap on
  command: swapon -a
  when: ansible_swaptotal_mb < 1
  
- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
  when: ansible_swaptotal_mb < 1
