- name: 'installing docker-py'
  pip: name=docker state=latest
  become: true
  tags: 'sinkers::docker'
  
- name: 'installing docker-compose'
  pip: name=docker-compose state=latest
  become: true
  tags: 'sinkers::docker'

- name: 'starting up docker'
  systemd:
    state: started
    name: docker
    daemon_reload: no
    enabled: yes
  tags: 'sinkers::docker'
