- name: 'create elasticsearch folder'
  file:
    path: "{{ elasticsearch_directory }}"
    state: directory
    mode: 0755
  tags: 'collector::elasticsearch'

- name: 'increase vm.max_map count'
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
  tags: 'collector::elasticsearch'

- name: 'setting up elasticsearch cluster'
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
  with_items: "{{elasticsearch_files}}"
  tags: 'collector::elasticsearch'
  
- name: 'starting up elasticsearchd'
  systemd:
    state: started
    name: elasticsearchd
    daemon_reload: yes
    enabled: yes
  tags: 'collector::elasticsearch'

- name: 'reloading elasticsearch service'
  systemd:
    state: restarted
    name: elasticsearchd
    daemon_reload: yes
    enabled: yes
  when: elasticsearch_restart | default("false") | match("true")
  tags: 'collector::elasticsearch'

