- stat:
    path: "{{ role_path }}/files/sinker_registry_api/gocode"
  register: gocode_folder
  delegate_to: 127.0.0.1
  become: false
  tags: 'collector::sinkersapi'

- name: 'create gocode folder'
  file:
    path: "{{ role_path }}/files/sinker_registry_api/gocode"
    state: directory
  when: gocode_folder.stat.isdir is not defined 
  delegate_to: 127.0.0.1
  become: false
  tags: 'collector::sinkersapi'

- name: 'create path'
  file:
    path: "{{ role_path }}/files/sinker_registry_api/gocode/src/bitbucket.org/fseros/"
    recurse: "yes"
    state: directory
  when: gocode_folder.stat.isdir is not defined
  become: false
  delegate_to: 127.0.0.1
  tags: 'collector::sinkersapi'

- name: 'get sinker_registry_api repo'
  git:
      repo: 'git@bitbucket.org:fseros/sinker_registry_api.git'
      dest: "{{ role_path }}/files/sinker_registry_api/gocode/src/bitbucket.org/fseros/sinker_registry_api"
      ssh_opts: "-o StrictHostKeyChecking=no"
      version: 0.0.1    
  when: gocode_folder.stat.isdir is not defined 
  become: false
  delegate_to: 127.0.0.1
  tags: 'collector::sinkersapi'

- name: 'get golang compiler'
  include_role:
        name: ansible-go
  become: true
  delegate_to: 127.0.0.1
  tags: 'collector::sinkersapi'

- name: 'pack application'
  shell: "export GOPATH={{ role_path }}/files/sinker_registry_api/gocode/; cd $GOPATH/src/bitbucket.org/fseros/sinker_registry_api && glide install && bee pack "
  become: false
  delegate_to: 127.0.0.1
  tags: 'collector::sinkersapi'

- name: 'setting up sinkerapi'
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
  with_items: "{{sinkerapi_files}}"
  tags: 'collector::sinkerapi'