- name: 'sysdig | retrieve apt-key'
  apt_key:
      url: "{{ sysdig_repo_key_url }}"
      id: "{{ sysdig_repo_key_id }}"  
      
- name: 'sysdig | setup apt repo'
  apt_repository:
      repo: "deb http://download.draios.com/stable/deb stable-$(ARCH)/"
      state: present

- name: 'get linux sources'
  apt: name=linux-source state=present
  tags: 'collector::sysdig'
- name: 'get linux sources'
  apt: name=linux-kernel-headers state=present
  tags: 'collector::sysdig'
- name: 'updating repo'
  apt: update_cache=yes
  tags: 'collector::sysdig'
- name: 'installing sysdig'
  apt:
    name: "sysdig"
    state: "present"
  tags: 'collector::sysdig'
- name: 'testing if sysdig works'
  become: yes
  command: sysdig-probe-loader
  tags: 'collector::sysdig'
- name: 'setting up sysdig as a service'
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
  tags: 'collector::sysdig'
  with_items: "{{sysdig_files}}"
