#!/bin/bash
### BEGIN INIT INFO
# Provides: elasticsearchd
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop elasticsearch cluster
### END INIT INFO

set -eufo pipefail

DESC="elasticsearch daemon"
NAME="elasticsearchd"
PIDFILE="/var/run/elasticsearchd.pid"
touch $PIDFILE
KPID=$(cat $PIDFILE)

do_start() {
    touch $PIDFILE
    if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
      logger -t info [$NAME] $NAME already running
    else
      docker system prune -f
      cd /var/run/services/elasticsearch
      docker-compose up &
      echo $! > $PIDFILE
      sleep 10
    fi
}

do_stop() {
 echo "Stopping $NAME";
 if [ -n "${KPID}" -a -d "/proc/${KPID}" ];then
     kill $KPID
     cd /var/run/services/elasticsearch
     docker-compose stop
 fi
}

case "$1" in
   start)
     do_start
     ;;
   stop)
     do_stop
     ;;
   restart)
     do_stop
     do_start
     ;;
   *)
     echo "Usage: /etc/init.d/$NAME start|stop"
     exit 1
     ;;
esac

exit 0

