- hosts: '!newjoiners'
  vars:
    traces_collector_host: "collector"
    ssh_keyname: "traces_access_key"
  tasks:
            
  - name: Generate password for new user
    shell: /usr/bin/openssl rand -base64 32
    register: user_password

  - name: Generate encrypted password
    shell: mkpasswd --method=SHA-512 {{ user_password.stdout }}
    register: encrypted_user_password

  - name: create traces folder
    file:
      path: /var/log/traces
      state: directory
      mode: 0755

  - name: creating ansible user in sinkers
    user:
      name: file
      generate_ssh_key: yes
      system: yes
      shell: /bin/bash
      append: yes
      home: /var/log/traces
      createhome: no       
      password: "{{ encrypted_user_password.stdout }}"
    register: newuser
    when: "'sinkers' in group_names"
            
            
  - name: creating ansible user in collector
    user:
      name: file
      generate_ssh_key: yes
      system: yes
      shell: /bin/bash
      append: yes        
      createhome: yes      
      password: "{{ encrypted_user_password.stdout }}"
    register: newuser
    when: "traces_collector_host in group_names"

  - name: 'fetching public key for files'
    fetch:
        src: "/home/file/.ssh/id_rsa.pub"
        dest: "{{inventory_dir}}/storage/file_ssh_keys/"
        flat: yes
    when: "traces_collector_host in group_names"

  - name: Set authorized key
    authorized_key:
      user: file
      state: present
      key: "{{ lookup('file', inventory_dir + '/storage/file_ssh_keys/id_rsa.pub') }}"
    when: "'sinkers' in group_names"


  tags: fileRetrieval

