- hosts: '!newjoiners'
  any_errors_fatal: true
  roles:
      - { role: common, become: true }
      - { role: collector, become: true, when: "'collector' in group_names" }
      - { role: sinkers, become: true, when: "'sinkers' in group_names" }
  tags: 'common::all'