- name: 'installing docker-py'
  pip: name=docker state=latest
  become: true
  tags: 'sinkers::docker'

- name: 'installing docker-compose'
  pip: name=docker-compose state=latest
  become: true
  tags: 'sinkers::docker'

- name: 'create Docker image directory'
  file:
    path: "{{ container_directory }}"
    state: directory
    mode: 0755
  tags: 'sinkers::docker'

- name: 'setting up containers as a service'
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
  with_items: "{{container_files}}"
  tags: 'sinkers::docker'

- name: 'building base image'
  shell:  cd {{container_directory}} && docker build -f {{container_directory}}/Dockerfile-base -t servicebase:0.0.1 .
  tags: 'sinkers::docker'
  
- name: 'starting up containersvc'
  systemd:
    state: started
    name: containersvc
    daemon_reload: no
    enabled: yes
  tags: 'sinkers::docker'

- name: 'reloading containersvc service'
  command: /usr/local/sbin/containersvc stop
  when: docker_rebuild_force | default("false") | match("true")
  tags: 'sinkers::docker'

