- name: ' falco | retrieve apt-key'
  apt_key:
      url: "{{ sysdig_repo_key_url }}"
      id: "{{ sysdig_repo_key_id }}"

- name: 'falco | setup apt repo'
  apt_repository:
      repo: "deb http://download.draios.com/stable/deb stable-$(ARCH)/"
      state: present


- name: 'installing falco'
  apt: 
    name: falco=0.6.0 
    state: present
  tags: 'sinkers::falco'

- name: 'setting up falco driver'
  command: falco-probe-loader
  become: yes
  tags: 'sinkers::falco'

- stat:
    path: "{{ role_path }}/files/gocode"
  register: gocode_folder
  tags: 'sinkers::falco'

- name: 'create gocode folder'
  file:
    path: "{{ role_path }}/files/gocode"
    state: directory
  when: gocode_folder.stat.isdir is not defined 
  tags: 'sinkers::falco'

- name: 'get container_recycler repo'
  git:
      repo: 'git@bitbucket.org:fseros/container_recycler.git'
      dest: "{{ role_path }}/files/gocode/src/bitbucket.org/fseros/container_recycler"
      ssh_opts: "-o StrictHostKeyChecking=no"
      version: 0.0.5    
  when: gocode_folder.stat.isdir is not defined 
  become: false
  delegate_to: 127.0.0.1
  tags: 'sinkers::falco'

  
- name: 'get golang compiler'
  include_role:
        name: ansible-go
  become: true
  delegate_to: 127.0.0.1
  tags: 'sinkers::falco'

- name: 'compile container_recycler'
  shell: "export GOPATH={{ role_path }}/files/gocode/; cd $GOPATH/src/bitbucket.org/fseros/container_recycler && make "
  become: false
  delegate_to: 127.0.0.1
  tags: 'sinkers::falco'

- name: 'setting up falco and falco rules'
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
  with_items: "{{falco_files}}"
  notify: restart falco
  tags: 'sinkers::falco'


- name: 'starting up falco'
  systemd:
    state: started
    name: falco
    daemon_reload: yes
    enabled: yes
  tags: 'sinkers::falco'

