  - name: Generate password for new user
    shell: /usr/bin/openssl rand -base64 32
    register: user_password
    tags: 'sinkers::fileretrieval'

  - name: Generate encrypted password
    shell: mkpasswd --method=SHA-512 {{ user_password.stdout }}
    register: encrypted_user_password
    tags: 'sinkers::fileretrieval'

  - name: create traces folder
    file:
      path: /var/log/traces
      state: directory
      mode: 0755
    tags: 'sinkers::fileretrieval'

  - name: creating ansible user in sinkers
    user:
      name: file
      generate_ssh_key: yes
      system: yes
      shell: /bin/bash
      append: yes
      home: /var/log/traces
      createhome: no       
      password: "{{ encrypted_user_password.stdout }}"
    register: newuser
    tags: 'sinkers::fileretrieval'
    #notify: register ssh keys in sinkers api

  - name: Set authorized key
    authorized_key:
      user: file
      state: present
      key: "{{ lookup('file', inventory_dir + '/storage/file_ssh_keys/id_rsa.pub') }}"
    tags: 'common::fileretrieval'